name: Notify Slack
run-name: Notify Slack [${{ github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]

on:
  schedule:
  - cron: 0 15,19,23 * * 1-6
  workflow_dispatch:
  
jobs:
  github-notifier:
    runs-on: ubuntu-latest
    steps:
    - uses: krauters/github-notifier@main
      with:
        github-token: ${{ secrets.GH_TOKEN_GH_NOTIFIER }}
        channels: C077T9CKZ24
        slack-token: ${{ secrets.SLACK_TOKEN_GH_NOTIFIER }}
        with-drafts: true
        repository-filter: pike-cdk, pike-mobile, pike-backend, pike-web, .github, .github-private
